### ISSUE TITLE
sparse listing for atk-sc3

### ISSUE THREAD

**Issue by joslloand** [capital-G/baryon#8] opened 2023-11-06 19:51 UTC
The listing for [atk-sc3](https://baryon.supercollider.online/project/atk-sc3) appears very sparse, in particular reporting:

> Project has no README file.

In actuality, the [atk-sc3 quark ](https://github.com/ambisonictoolkit/atk-sc3) is fairly verbose. (README [here](https://github.com/ambisonictoolkit/atk-sc3/blob/master/README.md).)

Perhaps there is some reason baryon isn't _correctly parsing_ the atk-sc3 repository?

**Comment by capital-G** [comment] 2023-11-06 21:13
Thanks for the hint, this seems indeed an interesting bug - I just ran the import script again and the following message error popped up.

```python
ERROR 2023-11-06 20:53:54,701 scraper 21692 139667859716992 Found error on atk-sc3 (https://github.com/ambisonictoolkit/atk-sc3): 'charmap' codec can't decode byte 0x81 in position 2464: character maps to <undefined>
```

I need to guess the encoding of the README b/c not everyone is using utf-8 and it seems [chardet](https://github.com/chardet/chardet) guesses wrong which results in an error.

https://github.com/capital-G/baryon/blob/0d91f1514bc51a649af57065772aba060dfb286a/baryon/quarks/sc/extractor.py#L206-L218

But running the same code via in interpreter (threfore non-async) does work as intended, so maybe there is something wrong with using the async runtime for CPU heavy computations.

I think the best way would be to only rely on chardet to guess the encoding if it fails to open as utf-8.

edit: interestingly enough, on my local version running on my mac, `atk-sc3` has a readme content.

**Comment by capital-G** [comment] 2023-11-06 21:45
I tried out fixing this in a branch

https://github.com/capital-G/baryon/blob/d3c852f67ed063a41367b9451be716cd78337b11/baryon/quarks/sc/extractor.py#L206-L223

but still get the same error

```python
ERROR 2023-11-06 21:30:57,969 scraper 16 139940261129088 Found error on atk-sc3 (https://github.com/ambisonictoolkit/atk-sc3): 'charmap' codec can't decode byte 0x81 in position 2464: character maps to <undefined>
```

Really strange...

**Comment by joslloand** [comment] 2023-11-06 22:38
Hmm....

I'm not sure if this observation will help, but [quarks-web](https://github.com/capital-G/quarks-web) seems to correctly parse.

**Comment by capital-G** [comment] 2023-11-13 11:17
Fixed via https://github.com/capital-G/baryon/pull/9/commits/b61ff2e4a0d5aab57573b4be8fa180c1aceffb8b, see https://baryon.supercollider.online/project/atk-sc3

**Closed as completed** 2023-11-13 11:17 UTC

**Comment by joslloand** [comment] 2023-11-16 20:10
> Fixed via https://github.com/capital-G/baryon/commit/b61ff2e4a0d5aab57573b4be8fa180c1aceffb8b, see https://baryon.supercollider.online/project/atk-sc3

Hurrah!
